@rootApi = http://localhost:8000/api/v1

@adminApi = {{rootApi}}/admin

@categoryApi = {{rootApi}}/category

======== server test ========
### get method
GET {{rootApi}}

========== admin ============
### get admin
GET {{adminApi}}

### post method
POST {{adminApi}}
Content-Type: application/json

{
    "fName": "Laxman",
    "lName": "Magar",
    "phone": "0987654321",
    "address": "Brisbane",
    "email": "laxman@email.com",
    "password": "qwertyuiop"
}

### put mthod
PUT {{adminApi}}
Content-Type: application/json

{

}

### Delete method
DELETE {{adminApi}}
Content-Type: application/json

{

}


============= category ===========
###get category
GET {{categoryApi}}

### POST category
POST {{categoryApi}}
Content-Type: application/json

{
    "title": "Mobile Devices For Apple"
}