@rootApi = http://localhost:8000/api/v1

@adminApi = {{rootApi}}/admin

@categoryApi = {{rootApi}}/category

======== server test ========
### get method
GET {{rootApi}}

========== admin ============
### get admin
GET {{adminApi}}

### post method
POST {{adminApi}}
Content-Type: application/json

{
    "fName": "Laxman",
    "lName": "Magar",
    "phone": "0987654321",
    "address": "Brisbane",
    "email": "laxman@email.com",
    "password": "qwertyuiop"
}

### put mthod
PUT {{adminApi}}
Content-Type: application/json

{

}

### Delete method
DELETE {{adminApi}}
Content-Type: application/json

{

}

============= category ===========
###get category
GET {{categoryApi}}
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2OTA2NzcxODQsImV4cCI6MTY5MDY3ODA4NH0.hzlnYlaj1EFU-g9ZTyYX1CyR_yVQmtEqVdh3kj5d_3I

### POST category
POST {{categoryApi}}
Content-Type: application/json

{
    "title": "Mobile Devices For Apple"
}

========== login ============

### get admin
GET {{rootApi}}/login

### post method
POST {{rootApi}}/login
Content-Type: application/json

{
    "email": "laxman@email.com",
    "password": "qwertyuiop"
}

### put mthod
PUT {{rootApi}}/login
Content-Type: application/json

{

}

### Delete method
DELETE {{rootApi}}/login
Content-Type: application/json

{

}